pub mod announcement_service;
pub mod auth_service;
pub mod period_service;
pub mod registration_service;
pub mod school_service;
pub mod scoring_service;
pub mod selection_service;
pub mod user_service;
pub mod verification_service;
